"""Remove unique constraint from user_id and task_id in locations table

Revision ID: 62e84b37a6ce
Revises: a9d984632e41
Create Date: 2024-12-11 20:25:19.435373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e84b37a6ce'
down_revision: Union[str, None] = 'a9d984632e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locations_task_id_key', 'locations', type_='unique')
    op.drop_constraint('locations_user_id_key', 'locations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('locations_user_id_key', 'locations', ['user_id'])
    op.create_unique_constraint('locations_task_id_key', 'locations', ['task_id'])
    # ### end Alembic commands ###
