"""update tasks table

Revision ID: 637f5efd33d5
Revises: 62b583a2b984
Create Date: 2024-11-28 23:26:27.476411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '637f5efd33d5'
down_revision: Union[str, None] = '62b583a2b984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_title_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_title_key', 'tasks', ['title'])
    # ### end Alembic commands ###
