"""Setting init=false in relationships in locations table

Revision ID: c48f9f1c07c5
Revises: 62e84b37a6ce
Create Date: 2024-12-11 20:45:24.748012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48f9f1c07c5'
down_revision: Union[str, None] = '62e84b37a6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
